GCP Deploy CI/CD Test

diff --git a/.github/workflows/Sheela_gcp_deploy.yml b/.github/workflows/Sheela_gcp_deploy.yml
--- a/.github/workflows/Sheela_gcp_deploy.yml
+++ b/.github/workflows/Sheela_gcp_deploy.yml
@@ -1,2 +1,49 @@
-STARTUP_SCRIPT_PATH: startup.sh
-SETUP_SCRIPT_PATH: setup.sh
+name: Create VM Image
+
+on:
+  push:
+    branches:
+      - Sheela-deployment  # Trigger the workflow on push to the specified branch
+
+env:
+  PROJECT_ID: iconic-vine-438222-u6
+  IMAGE_NAME: bank-marketing-mlops-image
+  IMAGE_FAMILY: bank-marketing-mlops-family
+  IMAGE_DESCRIPTION: "Image for Bank Marketing MLOps App"
+  INSTANCE_TEMPLATE_NAME: bank-marketing-template
+  ZONE: us-central1-a
+  SOURCE_INSTANCE: bank-marketing-prediction-mlops-instance
+  SETUP_SCRIPT_PATH: setup.sh
+  STARTUP_SCRIPT_PATH: startup.sh
+
+jobs:
+  test-script-copy:
+    runs-on: ubuntu-latest
+
+    steps:
+      - name: Checkout Repository
+        uses: actions/checkout@v2
+
+      - name: Authenticate to Google Cloud
+        uses: google-github-actions/auth@v1
+        with:
+          credentials_json: ${{ secrets.GCP_SA_KEY }}
+
+      - name: Set up Google Cloud SDK
+        uses: google-github-actions/setup-gcloud@v1
+        with:
+          project_id: ${{ env.PROJECT_ID }}
+          install_components: gcloud
+
+      - name: Copy Startup and Setup Scripts to Instance
+        run: |
+          echo "Copying setup.sh..."
+          gcloud compute scp ./${{ env.SETUP_SCRIPT_PATH }} ${{ env.SOURCE_INSTANCE }}:/home/ --zone=${{ env.ZONE }} || { echo "Failed to copy setup.sh. Exiting."; exit 1; }
+
+          echo "Copying startup.sh..."
+          gcloud compute scp ./${{ env.STARTUP_SCRIPT_PATH }} ${{ env.SOURCE_INSTANCE }}:/home/ --zone=${{ env.ZONE }} || { echo "Failed to copy startup.sh. Exiting."; exit 1; }
+
+      - name: Validate Script Paths on VM
+        run: |
+          echo "Validating script paths on the VM..."
+          gcloud compute ssh ${{ env.SOURCE_INSTANCE }} --zone=${{ env.ZONE }} --command="ls -lh /home/${{ env.SETUP_SCRIPT_PATH }} && ls -lh /home/${{ env.STARTUP_SCRIPT_PATH }}"
